<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Proiect sda</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ProiectSDA_files/libs/clipboard/clipboard.min.js"></script>
<script src="ProiectSDA_files/libs/quarto-html/quarto.js"></script>
<script src="ProiectSDA_files/libs/quarto-html/popper.min.js"></script>
<script src="ProiectSDA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ProiectSDA_files/libs/quarto-html/anchor.min.js"></script>
<link href="ProiectSDA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ProiectSDA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ProiectSDA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ProiectSDA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ProiectSDA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proiect sda</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<style type="text/css">
.justify {
  text-align: justify !important
}
</style>
</div>
<section id="descrierea-problemei" class="level2">
<h2 class="anchored" data-anchor-id="descrierea-problemei">1.Descrierea problemei</h2>
<div class="justify">
<p>Compania care constituie subiectul de cercetare în cadrul proiectului se numește IBM- International Business Machines (Corporation). Veterană în domeniul tehnologiei, aceasta și-a pus amprenta în istoria marilor corporații prin invenții fără de care cele mai uzuale activităti omenești nu ar mai fi posibile. În prezent problema principală cu care se confruntă este reprezentată de creșterea epuizării angajaților din cauza volumului mare de muncă.</p>
<p>Cu ajutorul acestui set de date, care reflectă performanța angajaților IBM, ne propunem să realizăm o previziune a numărului de angajați care vor deveni epuizați. Pentru aceasta, vom aplica regresia logistică binomială în funcție de venitul lunar și vechime; și KNN asociat problemei de clasificare.</p>
<section id="importanța-problemei" class="level2">
<h2 class="anchored" data-anchor-id="importanța-problemei">2.Importanța problemei</h2>
<section id="de-ce-e-importantă-problema-pentru-firmă" class="level3">
<h3 class="anchored" data-anchor-id="de-ce-e-importantă-problema-pentru-firmă">De ce e importantă problema pentru firmă?</h3>
<p>Productivitatea angajaților se reflectă în mod direct în performanța companiei. Un angajat suprasolicitat nu își îndeplinește sarcinile în mod corespunzător ceea ce va afecta rezultatele companiei într-un mod negativ. Astfel, IBM nu se va ridica la așteptările clienților, crescând riscul de a-și pierde clientela.</p>
</section>
<section id="de-ce-e-importantă-problema-pentru-noi" class="level3">
<h3 class="anchored" data-anchor-id="de-ce-e-importantă-problema-pentru-noi">De ce e importantă problema pentru noi?</h3>
<p>Din perspectiva viitorilor angajați există reținerea de a intra într-un mediu toxic de supraexploatare a personalului.</p>
<p>În concluzie, problema identificată afectează performanța firmei atât în plan intern cât și extern.</p>
</section>
</section>
<section id="ce-măsuri-s-au-luat-pentru-combaterea-problemei" class="level2">
<h2 class="anchored" data-anchor-id="ce-măsuri-s-au-luat-pentru-combaterea-problemei">3.Ce măsuri s-au luat pentru combaterea problemei?</h2>
<section id="măsuri-la-nivel-global" class="level3">
<h3 class="anchored" data-anchor-id="măsuri-la-nivel-global">Măsuri la nivel global</h3>
<p>În cadrul tuturor companiilor există riscul de suprasolicitare a angajaților, motiv pentru care au trebuit să adopte diverse măsuri precum: comunicarea constantă între angajați și conducere, suport, beneficii salariale, oferirea de tool-uri pentru eficientizarea sarcinilor de muncă.</p>
</section>
<section id="măsuri-luate-de-ibm" class="level3">
<h3 class="anchored" data-anchor-id="măsuri-luate-de-ibm">Măsuri luate de IBM</h3>
<p>Pentru a reduce riscul epuizării angajaților IBM a luat următoarele măsuri: training, program flexibil de lucru, posibilitatea de a lucra online, beneficii egale pentru toți angajații indiferent de rasă/ etnie.</p>
</section>
<section id="studii-relevante-cu-privire-la-analizarea-gradului-de-epuizare-al-angajaților-ibm" class="level3">
<h3 class="anchored" data-anchor-id="studii-relevante-cu-privire-la-analizarea-gradului-de-epuizare-al-angajaților-ibm">Studii relevante cu privire la analizarea gradului de epuizare al angajaților IBM</h3>
<p>În studiul realizat de Shenghuan Yang de la Jiangxi University of Finance and Economics și Md Tariqul Islam de la Syracuse University s-au căutat principalele motive pentru care angajații aleg să demisioneze din IBM. Metodele utilizate de aceștia s-au concentrat pe exploatarea arborilor de decizie, găsind venitul lunar, vârsta și numărul de companii la care au lucrat ca având un impact semnificativ asupra angajaților. În continuare au clasificat persoanele în două grupuri prin utilizarea k-means clustering. În cele din urmă au efectuat o analiză cantitativă și anume o regresie logistică binară din care a rezultat că uzura persoanelor care au călătorit frecvent a fost de 2,4 ori mai mare decât cea a persoanelor care călătoreau rar. De asemenea, au constatat faptul că angajații care lucrează în domeniul resurselor umane au o tendință mai mare de a pleca.</p>
</section>
</section>
</div>
</section>
<section id="soluție-rezultate" class="level2">
<h2 class="anchored" data-anchor-id="soluție-rezultate">4. Soluție + rezultate</h2>
<div class="justify">
<p>Respectivul set de date a fost preluat de pe data.world și conține 14 atribute și 1470 de entități/indivizi. Vârsta, frecvența călătoriilor în interes de serviciu și sexul sunt atribute categoriale formate din 2 sau 3 clase, iar restul de coloane conține date cantitative. Scopul cercetării în această zonă este acela de a determina ce factori contribuie predominant la apariția uzurii utilizând tehnici de învățare precum clasificarea și regresia pentru a crea modele de predicție din datele colectate. Am prelucrat setul de date, adăugând o nouă coloană denumită EmployeeNr astfel încât fiecare angajat să aibă un id unic.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Pachete</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("dplyr")</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("caTools")</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("class")</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(class)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("rpart")</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("rpart.plot")</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("e1071")</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Incarcarea datelor</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dateSDA<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"date_proiect_sda.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">","</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(dateSDA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Prelucrarea setului de date</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mat <span class="ot">&lt;-</span> <span class="fu">matrix</span> (<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">1470</span>),<span class="at">nrow=</span><span class="dv">1470</span>, <span class="at">ncol=</span><span class="dv">1</span>, <span class="at">byrow=</span><span class="cn">FALSE</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#View(mat)</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"EmployeeNr"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>date <span class="ot">&lt;-</span> <span class="fu">data.frame</span> (mat, dateSDA)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#View(date)</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>date_proiect <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(date)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(date_proiect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,470 × 14] (S3: tbl_df/tbl/data.frame)
 $ EmployeeNr             : int [1:1470] 1 2 3 4 5 6 7 8 9 10 ...
 $ Age                    : int [1:1470] 41 49 37 33 27 32 59 30 38 36 ...
 $ Attrition              : chr [1:1470] "Yes" "No" "Yes" "No" ...
 $ BusinessTravel         : chr [1:1470] "Travel_Rarely" "Travel_Frequently" "Travel_Rarely" "Travel_Frequently" ...
 $ DistanceFromHome       : int [1:1470] 1 8 2 3 2 2 3 24 23 27 ...
 $ Gender                 : chr [1:1470] "Female" "Male" "Male" "Female" ...
 $ MonthlyIncome          : int [1:1470] 5993 5130 2090 2909 3468 3068 2670 2693 9526 5237 ...
 $ NumCompaniesWorked     : int [1:1470] 8 1 6 1 9 0 4 1 0 6 ...
 $ TotalWorkingYears      : int [1:1470] 8 10 7 8 6 8 12 1 10 17 ...
 $ TrainingTimesLastYear  : int [1:1470] 0 3 3 3 3 2 3 2 2 3 ...
 $ YearsAtCompany         : int [1:1470] 6 10 0 8 2 7 1 1 9 7 ...
 $ YearsInCurrentRole     : int [1:1470] 4 7 0 7 2 7 0 0 7 7 ...
 $ YearsSinceLastPromotion: int [1:1470] 0 1 0 3 2 3 0 0 1 7 ...
 $ YearsWithCurrManager   : int [1:1470] 5 7 0 0 2 6 0 0 8 7 ...</code></pre>
</div>
</div>
<section id="regresia-logistică-binomială" class="level3">
<h3 class="anchored" data-anchor-id="regresia-logistică-binomială">4.1.Regresia logistică binomială</h3>
<div class="justify">
<p>Pentru aplicarea regresiei logistice de tip binomial, am utilizat, ca variabila dependenta, coloana Attrition, iar ca variabile independente, MonthlyIncome (venitul solicitantului) si TotalWorkingYears (numar ani vechime).</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(date_proiect<span class="sc">$</span>Attrition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  No  Yes 
1233  237 </code></pre>
</div>
</div>
<div class="justify">
<p>În cadrul setului de date, 1233 de persoane nu sunt epuizate, iar 237 de persoane resimt oboseala din cauza volumului mare de muncă.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crearea variabilei factor </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>date_proiect<span class="sc">$</span>Attrition.f<span class="ot">&lt;-</span><span class="fu">factor</span>(date_proiect<span class="sc">$</span>Attrition)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(date_proiect)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crearea setului de antrenare si testare</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">88</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(date_proiect)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>split<span class="ot">=</span><span class="fu">sample.split</span>(date_proiect<span class="sc">$</span>Attrition.f, <span class="at">SplitRatio=</span><span class="fl">0.75</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>setantrenare<span class="ot">&lt;-</span><span class="fu">subset</span>(date_proiect, split<span class="sc">==</span><span class="cn">TRUE</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>settestare<span class="ot">&lt;-</span><span class="fu">subset</span>(date_proiect, split<span class="sc">==</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>plot<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>date_proiect, <span class="fu">aes</span>(<span class="at">x=</span>date_proiect<span class="sc">$</span>MonthlyIncome, <span class="at">y=</span>date_proiect<span class="sc">$</span>TotalWorkingYears, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span>Attrition.f))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>plot<span class="ot">&lt;-</span>plot<span class="sc">+</span><span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size=</span><span class="dv">5</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Use of `date_proiect$MonthlyIncome` is discouraged.
ℹ Use `MonthlyIncome` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Use of `date_proiect$TotalWorkingYears` is discouraged.
ℹ Use `TotalWorkingYears` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ProiectSDA_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="justify">
<p>În figura de mai sus, se poate observa și vizual distribuția persoanelor epuizate și în formă, în funcție de venit și vechimea în muncă.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Model de regresie binomiala</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">glm</span>(Attrition.f<span class="sc">~</span>MonthlyIncome<span class="sc">+</span>TotalWorkingYears, <span class="at">data=</span>setantrenare, <span class="at">family=</span>binomial)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Attrition.f ~ MonthlyIncome + TotalWorkingYears, 
    family = binomial, data = setantrenare)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.8259  -0.6594  -0.5633  -0.3299   2.5840  

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -8.297e-01  1.581e-01  -5.249 1.53e-07 ***
MonthlyIncome     -6.704e-05  3.416e-05  -1.962   0.0497 *  
TotalWorkingYears -4.453e-02  1.937e-02  -2.299   0.0215 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 974.94  on 1102  degrees of freedom
Residual deviance: 937.82  on 1100  degrees of freedom
AIC: 943.82

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)     MonthlyIncome TotalWorkingYears 
        0.4361678         0.9999330         0.9564453 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(date_proiect<span class="sc">$</span>Attrition.f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Yes
No    0
Yes   1</code></pre>
</div>
</div>
<div class="justify">
<p>Prin intermediul acestui output pot fi evidențiate următoarele idei:</p>
<p><strong>1</strong>.Forma ecuației de regresie:</p>
<p><strong>Ln(p/1−p) = -0.82972823 – 0.00006704 * MonthlyIncome - 0.04453172 * TotalWorkingYears</strong></p>
<p>Unde: p = probabilitatea ca o persoană să nu fie epuizata (Attrition = No), conform venitului și a vechimii;</p>
<p>1-p = probabilitatea ca o persoană să fie epuizată (Attrition = Yes), conform venitului și a vechimii.</p>
<p>Această ecuație indică faptul că ambele variabile afectează în mod negativ raportul Ln(p/1−p). Astfel, o creștere cu o unitate a venitului generează scăderea raportului șanselor ca o persoana sa fie epuizata cu 0.00006704 unități. Asemanator, o crestere cu o unitate a vechimii produce o scădere a șanselor ca persoana să fie epuizată cu 0.04453172 unități. Din punctul nostru de vedere, rezultatele obținute nu corespund așteptărilor noastre.</p>
<p><strong>2</strong>.Devianța reziduală în valoare de 937.82 este mai mică decât devianța nulă egală cu 974.94, ceea ce înseamnă că modelul este unul relativ bun.</p>
<p><strong>3</strong>.În ceea ce privește coeficienții funcției exponențiale, putem afirma faptul că: – Probabilitatea (Șansele) ca o persoană să nu fie epuizată crește de 0.9999330 ori dacă venitul persoanei crește cu 1 unitate. Raportul șanselor = p/1−p = 0.9999330<br>
– Probabilitatea (Șansele) de a nu achita împrumutul crește de 0.9564453 ori dacă rata dobânzii crește cu 1 unitate. Raportul șanselor = 𝑝/ 1−p = 0.9564453</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>prob<span class="ot">&lt;-</span><span class="fu">predict</span>(model, settestare, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>pred<span class="ot">&lt;-</span><span class="fu">rep</span>(<span class="st">"Yes"</span>, <span class="fu">dim</span>(setantrenare)[<span class="dv">1</span>])</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>pred[prob<span class="sc">&gt;</span>.<span class="dv">5</span>]<span class="ot">=</span><span class="st">"No"</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Matricea de confuzie pentru setul de antrenare</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred, setantrenare<span class="sc">$</span>Attrition.f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
pred   No Yes
  Yes 925 178</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pred1<span class="ot">&lt;-</span><span class="fu">rep</span>(<span class="st">"Yes"</span>, <span class="fu">dim</span>(settestare)[<span class="dv">1</span>])</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>pred1[prob<span class="sc">&gt;</span>.<span class="dv">5</span>]<span class="ot">=</span><span class="st">"No"</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Matricea de confuzie pentru setul de testare</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred1, settestare<span class="sc">$</span>Attrition.f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
pred1  No Yes
  Yes 308  59</code></pre>
</div>
</div>
</section>
<section id="knn-pentru-clasificare" class="level3">
<h3 class="anchored" data-anchor-id="knn-pentru-clasificare">4.2. KNN pentru clasificare</h3>
<div class="justify">
<p>Pentru această problemă vom ține cont de ultimele coloane din setul nostru de date și anume”MonthlyIncome”,“NumCompaniesWorked”,“TotalWorkingYears”,“TrainingTimesLast Year”,“YearsAtCompany”,YearsInCurrentRole”,“YearsSinceLastPromotion”,“YearsWithCurrM anager”, și de asemenea vom considera coloana “Attrition” drept etichetă.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>date1 <span class="ot">&lt;-</span> date_proiect[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>)]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(date1)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>date1<span class="ot">&lt;-</span><span class="fu">data.frame</span>(date1,date<span class="sc">$</span>Attrition)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(date1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="justify">
<p>Extragem două eșantioane, corespunzătoare setului de antrenare în proporție de 80% din date și setului de testare în proporție de 20%. Dimensiunea setului de antrenare este de 1186 observații, iar a setului de testare de 284.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ind<span class="ot">&lt;-</span><span class="fu">sample</span>(<span class="dv">2</span>, <span class="fu">nrow</span>(date1), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.80</span>,<span class="fl">0.20</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>antrenare<span class="ot">&lt;-</span>date1[ind<span class="sc">==</span><span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(antrenare)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1186</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>testare<span class="ot">&lt;-</span>date1[ind<span class="sc">==</span><span class="dv">2</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(testare)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>etichetaantrenare<span class="ot">&lt;-</span> date1[ind<span class="sc">==</span><span class="dv">1</span>,<span class="dv">9</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(etichetaantrenare, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Yes No  Yes No  No  No  No  No  No  No 
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(etichetaantrenare)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1186</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>etichetatestare<span class="ot">&lt;-</span> date1[ind<span class="sc">==</span><span class="dv">2</span>,<span class="dv">9</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(etichetatestare, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] No No No No No No No No No No
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(etichetatestare)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 284</code></pre>
</div>
</div>
<div class="justify">
<p>Fixăm cei mai apropiați patru vecini ai oricărui obiect (k=4) și realizăm predicția. Matricea de confuzie ne comunică faptul că pe diagonala principală se află numărul de observații corect previzionate, iar în rest sunt erori. Mai exact 226 de angajați au fost corect catalogați ca fiind încă în putere, iar 9 angajați au fost corect catalogați ca fiind epuizați. 17,25% din observațiile setului de testare sunt incorect clasificate.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>predictie<span class="ot">&lt;-</span><span class="fu">knn</span>(<span class="at">train=</span>antrenare, <span class="at">test=</span>testare, <span class="at">cl=</span>etichetaantrenare, <span class="at">k=</span><span class="dv">4</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predictie, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] No No No No No No No No No No
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tab<span class="ot">&lt;-</span><span class="fu">table</span>(<span class="at">valori_reale=</span>etichetatestare, <span class="at">valori_previzionate=</span>predictie)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tab, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            valori_previzionate
valori_reale  No Yes
         No  226  12
         Yes  37   9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(etichetatestare<span class="sc">!=</span>predictie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1725352</code></pre>
</div>
</div>
<div class="justify">
<p>Rata de acuratețe a setului de testare este de 17,25%.</p>
</div>
</section>
</section>
<section id="concluzii" class="level2">
<h2 class="anchored" data-anchor-id="concluzii">5. Concluzii</h2>
<div class="justify">
<p>În urma aplicării regresiei logistice binomiale, modelul creat are toți cei trei coefiecienți semnificativi, asta însemnând că o creștere cu o unitate a venitului generează scăderea raportului șanselor ca o persoana sa fie epuizata cu 0.00006704 unități. Asemanator, o crestere cu o unitate a vechimii produce o scădere a șanselor ca persoana să fie epuizată cu 0.04453172 unități. De asemenea, previziunea realizată pe baza modelului ne indică, prin intermediul matricii de confuzie, faptul că, pe setul de antrenare, au fost previzionate corect 178 de persoane ca fiind epuizate, iar pe setul de testare, 59 de persoane. Deci, modelul nu este unul foarte relevant. Pe de altă parte, cu ajutorul analizei KNN pentru problema de clasificare, setând, în prealabil, 4 cei mai apropiați vecini, am obținut o previzionare corecta pentru 235 de persoane dintre care 226 nu sunt epuizate și 9 sunt epuizate, conform matricii de confuzie. Din cauza faptului că rata de acuratețe a setului de testare este mică, nu ne putem încrede pe deplin în analiză. Pe viitor, pentru previziuni mai bune se pot incerca arbori de decizie, regresia logistica multinomiala si o analiza SVM de clasificare.</p>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>